services:
  mongodb:
    image: mongo:latest
    container_name: sales_nosql
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret_pass