# Infrastructure Config
mongo.uri=mongodb://admin:secret_pass@localhost:27017
mongo.db=amazon_data
mongo.collection=sales
# Files
input.file=src/main/resources/AmazonSaleReport.csv
metadata.path=src/main/resources/pipeline-metadata.json